import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { fixture, as, actors, id, snapshot } from './invoice-lifecycle-fixture.js'
const helper = await readFile(new URL('../release/reconcile-legacy-payment.sql', import.meta.url), 'utf8')
const reconcile = db => db.query("SELECT pg_temp.reconcile_legacy_payment('INV-LIFE',200000,300000,$1,'reviewed synthetic ledger')", [actors.owner.auth])
test('legacy baseline unlocks cashier payment without replaying or changing old money', async t => {
  const db = await fixture(t)
  await db.exec(await readFile(new URL('../../supabase/security-stage2/012_payment_recovery.sql', import.meta.url), 'utf8'))
  const pay = () => as(db,'cashier',"SELECT pos_submit_payment($1,'INV-LIFE',100000,'transfer','synthetic') value",[id(880)])
  await assert.rejects(pay())
  const before = await snapshot(db)
  await db.exec(helper)
  await reconcile(db)
  const after = await snapshot(db)
  for (const table of Object.keys(before).filter(x => x!=='pos_security.payment_baselines')) assert.deepEqual(after[table],before[table],table)
  assert.equal((await pay())[0].value.result.paid,300000)
  assert.equal((await pay())[0].value.result.paid,300000)
  await assert.rejects(reconcile(db))
})
test('mismatched evidence and staff invocation cannot create a baseline', async t => {
  const db = await fixture(t)
  await db.exec(helper)
  await assert.rejects(db.query("SELECT pg_temp.reconcile_legacy_payment('INV-LIFE',199999,300001,$1,'reviewed synthetic ledger')",[actors.owner.auth]))
  await assert.rejects(as(db,'cashier',"SELECT pg_temp.reconcile_legacy_payment('INV-LIFE',200000,300000,$1,'reviewed synthetic ledger')",[actors.owner.auth]))
  assert.equal((await db.query('SELECT count(*)::int n FROM pos_security.payment_baselines')).rows[0].n,0)
})

test('missing legacy debt is restored once without new money and cashier can settle it', async t => {
  const db = await fixture(t, { mutate: db => db.exec('DELETE FROM debts') })
  await db.exec(await readFile(new URL('../../supabase/security-stage2/012_payment_recovery.sql', import.meta.url), 'utf8'))
  await db.exec(helper)
  const pay = () => as(db, 'cashier', "SELECT pos_submit_payment($1,'INV-LIFE',300000,'cash','synthetic settlement') value", [id(881)])
  await assert.rejects(pay())
  const before = await snapshot(db)
  await reconcile(db)
  const after = await snapshot(db)
  for (const table of Object.keys(before).filter(x => !['debts', 'customers', 'pos_security.payment_baselines'].includes(x))) assert.deepEqual(after[table], before[table], table)
  assert.equal(after.customers[0].row.total_debt, 300000)
  assert.equal(after.customers[0].row.total_spent, before.customers[0].row.total_spent)
  assert.equal(after.customers[0].row.total_transactions, before.customers[0].row.total_transactions)
  const identity = row => Object.fromEntries(Object.entries(row).filter(([key]) => !['total_debt', 'updated_at'].includes(key)))
  assert.deepEqual(identity(after.customers[0].row), identity(before.customers[0].row))
  assert.equal(after.debts.length, 1)
  assert.equal(after.debts[0].row.paid, 200000)
  assert.equal(after.debts[0].row.remaining, 300000)
  assert.equal(after['pos_security.payment_baselines'][0].row.initial_snapshot.restored_missing_debt, true)
  await assert.rejects(reconcile(db))
  assert.equal((await pay())[0].value.result.remaining, 0)
  assert.equal((await pay())[0].value.result.remaining, 0)
  assert.equal((await db.query('SELECT count(*)::int n FROM debt_payments')).rows[0].n, 1)
})

test('missing debt restoration rolls back on inconsistent cash evidence or stale amounts', async t => {
  const db = await fixture(t, { mutate: db => db.exec('DELETE FROM debts; DELETE FROM cash_movements') })
  await db.exec(helper)
  const before = await snapshot(db)
  await assert.rejects(reconcile(db))
  assert.deepEqual(await snapshot(db), before)
})

test('missing debt restoration rejects staff and stale expected balance without partial writes', async t => {
  const db = await fixture(t, { mutate: db => db.exec('DELETE FROM debts') })
  await db.exec(helper)
  const before = await snapshot(db)
  await assert.rejects(db.query("SELECT pg_temp.reconcile_legacy_payment('INV-LIFE',199999,300001,$1,'reviewed synthetic ledger')", [actors.owner.auth]))
  await assert.rejects(as(db, 'cashier', "SELECT pg_temp.reconcile_legacy_payment('INV-LIFE',200000,300000,$1,'reviewed synthetic ledger')", [actors.owner.auth]))
  assert.deepEqual(await snapshot(db), before)
})
